<script lang="ts">
  import { onMount } from 'svelte';
  import { Navbar, SignalCard } from '$lib/components';
  import { watchlist, notifications } from '$lib/stores/app';
  import { analysisApi } from '$lib/api/client';
  import type { Signal } from '$lib/api/client';
  import { RefreshCw, Filter, Zap } from 'lucide-svelte';

  let allSignals = $state<Signal[]>([]);
  let loading = $state(true);
  let filterType = $state<'ALL' | 'BUY' | 'SELL' | 'HOLD'>('ALL');

  const filteredSignals = $derived(
    filterType === 'ALL'
      ? allSignals
      : allSignals.filter(s => s.type === filterType)
  );

  async function fetchAllSignals() {
    loading = true;
    const signals: Signal[] = [];

    for (const item of $watchlist) {
      const { data } = await analysisApi.getSignals(item.symbol);
      if (data) {
        signals.push(...data);
      }
    }

    // Sort by timestamp (newest first)
    allSignals = signals.sort((a, b) =>
      new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );

    loading = false;
  }

  onMount(() => {
    fetchAllSignals();
  });

  const signalCounts = $derived({
    all: allSignals.length,
    buy: allSignals.filter(s => s.type === 'BUY').length,
    sell: allSignals.filter(s => s.type === 'SELL').length,
    hold: allSignals.filter(s => s.type === 'HOLD').length,
  });
</script>

<div class="flex flex-col h-full">
  <Navbar>
    {#snippet title()}
      <h1 class="text-xl font-semibold text-surface-900 dark:text-white">Signals</h1>
    {/snippet}
  </Navbar>

  <div class="flex-1 p-6 overflow-auto">
    <!-- Header -->
    <div class="flex flex-wrap items-center justify-between gap-4 mb-6">
      <div>
        <h2 class="text-2xl font-bold text-surface-900 dark:text-white">Trading Signals</h2>
        <p class="text-sm text-surface-500 dark:text-surface-400">
          AI-generated signals for your watchlist
        </p>
      </div>
      <button onclick={fetchAllSignals} disabled={loading} class="btn-secondary flex items-center space-x-2">
        <RefreshCw class="h-4 w-4 {loading ? 'animate-spin' : ''}" />
        <span>Refresh</span>
      </button>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
      <button
        onclick={() => filterType = 'ALL'}
        class="card p-4 text-left transition-all {filterType === 'ALL' ? 'ring-2 ring-primary-500' : ''}"
      >
        <p class="text-sm text-surface-500 dark:text-surface-400">All Signals</p>
        <p class="text-2xl font-bold text-surface-900 dark:text-white">{signalCounts.all}</p>
      </button>
      <button
        onclick={() => filterType = 'BUY'}
        class="card p-4 text-left transition-all {filterType === 'BUY' ? 'ring-2 ring-success-500' : ''}"
      >
        <p class="text-sm text-surface-500 dark:text-surface-400">Buy Signals</p>
        <p class="text-2xl font-bold text-success-500">{signalCounts.buy}</p>
      </button>
      <button
        onclick={() => filterType = 'SELL'}
        class="card p-4 text-left transition-all {filterType === 'SELL' ? 'ring-2 ring-danger-500' : ''}"
      >
        <p class="text-sm text-surface-500 dark:text-surface-400">Sell Signals</p>
        <p class="text-2xl font-bold text-danger-500">{signalCounts.sell}</p>
      </button>
      <button
        onclick={() => filterType = 'HOLD'}
        class="card p-4 text-left transition-all {filterType === 'HOLD' ? 'ring-2 ring-warning-500' : ''}"
      >
        <p class="text-sm text-surface-500 dark:text-surface-400">Hold Signals</p>
        <p class="text-2xl font-bold text-warning-500">{signalCounts.hold}</p>
      </button>
    </div>

    <!-- Signals List -->
    {#if loading}
      <div class="space-y-4">
        {#each Array(5) as _}
          <div class="card p-4">
            <div class="animate-pulse space-y-3">
              <div class="flex justify-between">
                <div class="h-5 w-24 bg-surface-200 dark:bg-surface-700 rounded"></div>
                <div class="h-5 w-16 bg-surface-200 dark:bg-surface-700 rounded"></div>
              </div>
              <div class="h-4 w-3/4 bg-surface-200 dark:bg-surface-700 rounded"></div>
              <div class="h-3 w-1/2 bg-surface-200 dark:bg-surface-700 rounded"></div>
            </div>
          </div>
        {/each}
      </div>
    {:else if filteredSignals.length === 0}
      <div class="card p-12 text-center">
        <Zap class="h-16 w-16 mx-auto text-surface-300 dark:text-surface-600 mb-4" />
        <h3 class="text-lg font-medium text-surface-900 dark:text-white mb-2">
          No {filterType !== 'ALL' ? filterType.toLowerCase() : ''} signals
        </h3>
        <p class="text-surface-500 dark:text-surface-400">
          Signals will appear here when generated by the analysis engine
        </p>
      </div>
    {:else}
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {#each filteredSignals as signal}
          <SignalCard {signal} />
        {/each}
      </div>
    {/if}
  </div>
</div>
