import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

// Firebase imports - used on all platforms
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
// Local notifications - only for mobile (web uses browser notifications)
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
// Firebase configuration generated by FlutterFire CLI
import 'firebase_options.dart';

import 'screens/home_screen.dart';
import 'screens/watchlist_screen.dart';
import 'screens/chart_screen.dart';
import 'screens/signals_screen.dart';
import 'screens/alerts_screen.dart';
import 'screens/risk_calculator_screen.dart';
import 'screens/settings_screen.dart';
import 'services/api_service.dart';
import 'services/websocket_service.dart';
import 'utils/theme.dart';
import 'utils/app_logger.dart';

// App-wide logger
final _logger = AppLogger('Main');

// Background message handler (mobile only - web uses service worker)
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  _logger.info('Handling background message: ${message.messageId}');
}

// Notifications plugin (mobile only - web uses browser notifications via service worker)
FlutterLocalNotificationsPlugin? _flutterLocalNotificationsPlugin;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Setup global error handling
  setupGlobalErrorHandling();
  _logger.info('App starting...');

  // Initialize Hive (works on all platforms)
  await Hive.initFlutter();

  // Initialize Firebase on all platforms
  await _initFirebase();

  runApp(const ProviderScope(child: MyApp()));
}

/// Initialize Firebase and notifications (platform-aware)
Future<void> _initFirebase() async {
  try {
    // Initialize Firebase with FlutterFire CLI generated options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    _logger.info('Firebase initialized on ${kIsWeb ? 'web' : 'mobile'}');

    // Request notification permissions (works on all platforms)
    final messaging = FirebaseMessaging.instance;
    final settings = await messaging.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );
    _logger.info('Notification permission: ${settings.authorizationStatus}');

    // Mobile-only: background handler and local notifications
    if (!kIsWeb) {
      FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

      // Initialize local notifications for mobile
      _flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

      const AndroidInitializationSettings initializationSettingsAndroid =
          AndroidInitializationSettings('@mipmap/ic_launcher');

      const InitializationSettings initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid,
      );

      await _flutterLocalNotificationsPlugin!.initialize(
        initializationSettings,
        onDidReceiveNotificationResponse: (NotificationResponse response) {
          _logger.info('Notification tapped: ${response.payload}');
        },
      );
      _logger.info('Local notifications initialized');
    } else {
      // Web: Get FCM token for push notifications
      try {
        final token = await messaging.getToken();
        _logger.info('FCM Web token obtained', token != null ? 'Token ready' : 'No token');
      } catch (e) {
        _logger.warning('FCM token not available (Firebase not configured?)');
      }
    }

    _logger.info('Firebase and notifications initialized');
  } catch (e, stack) {
    _logger.error('Failed to initialize Firebase', error: e, stackTrace: stack);
    // Don't crash the app - Firebase is optional for basic functionality
  }
}

class MyApp extends ConsumerStatefulWidget {
  const MyApp({super.key});

  @override
  ConsumerState<MyApp> createState() => _MyAppState();
}

class _MyAppState extends ConsumerState<MyApp> {
  @override
  void initState() {
    super.initState();
    // Setup Firebase messaging listeners (works on all platforms)
    _setupFirebaseMessaging();
  }

  void _setupFirebaseMessaging() {
    // Listen for foreground messages (works on web and mobile)
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      _logger.info('FCM message received in foreground', message.data);

      if (message.notification != null) {
        if (kIsWeb) {
          // Web: show browser notification (if permission granted)
          _logger.info('Web notification: ${message.notification!.title}');
          // Browser will show notification automatically via service worker
        } else {
          // Mobile: show local notification
          _showNotification(
            message.notification!.title ?? 'Trading Alert',
            message.notification!.body ?? '',
          );
        }
      }
    });

    // Listen for notification taps (works on web and mobile)
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      _logger.info('FCM message clicked', message.data);
      // TODO: Navigate to specific screen based on message data
    });
  }

  Future<void> _showNotification(String title, String body) async {
    // Only for mobile - web uses browser notifications via service worker
    if (kIsWeb || _flutterLocalNotificationsPlugin == null) return;

    const AndroidNotificationDetails androidDetails = AndroidNotificationDetails(
      'trading_alerts',
      'Trading Alerts',
      channelDescription: 'Alerts for trading signals and market events',
      importance: Importance.max,
      priority: Priority.high,
      showWhen: true,
    );

    const NotificationDetails notificationDetails = NotificationDetails(
      android: androidDetails,
    );

    await _flutterLocalNotificationsPlugin!.show(
      DateTime.now().millisecondsSinceEpoch.remainder(100000),
      title,
      body,
      notificationDetails,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AI Trading System',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.dark,
      home: const MainNavigator(),
    );
  }
}

class MainNavigator extends StatefulWidget {
  const MainNavigator({super.key});

  @override
  State<MainNavigator> createState() => _MainNavigatorState();
}

class _MainNavigatorState extends State<MainNavigator> {
  int _currentIndex = 0;

  final List<Widget> _screens = [
    const HomeScreen(),
    const WatchlistScreen(),
    const SignalsScreen(),
    const AlertsScreen(),
    const SettingsScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(
        index: _currentIndex,
        children: _screens,
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (index) => setState(() => _currentIndex = index),
        type: BottomNavigationBarType.fixed,
        selectedItemColor: Theme.of(context).colorScheme.primary,
        unselectedItemColor: Colors.grey,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.list),
            label: 'Watchlist',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.show_chart),
            label: 'Signals',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.notifications),
            label: 'Alerts',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
      ),
    );
  }
}
